platform :ios, '11.0'
inhibit_all_warnings!
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MyUiDemo' do
    config = use_native_modules!
    use_react_native!(
        :path => config[:reactNativePath],
        :hermes_enabled => false
    )
    
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
end

post_install do |installer|
    react_native_post_install(installer)
end
