platform :ios, '12.4'
inhibit_all_warnings!
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MyUiDemo' do
    config = use_native_modules!
    use_react_native!(
        :path => config[:reactNativePath],
        :hermes_enabled => false
    )
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        end
        case target.name
          when 'RCT-Folly'
            next
          else
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.4
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
                end
            end
        end

    end
end
